export const EMPLOYEES_REQUESTED = 'EMPLOYEES_REQUESTED';
export const EMPLOYEES_FETCHED = 'EMPLOYEES_FETCHED';
export const EMPLOYEES_RESET = 'EMPLOYEES_RESET';
export const DEPARTMENTS_REQUESTED = 'DEPARTMENTS_REQUESTED';
export const DEPARTMENTS_FETCHED = 'DEPARTMENTS_FETCHED';
export const DEPARTMENTS_RESET = 'DEPARTMENTS_RESET';
